title: Deep Magic PT-BR
description: Tradução PT-BR dos conteúdos do Deep Magic
theme: just-the-docs

# url: https://Fotkurz.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
